# coding: utf-8

"""
    BDL API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.years_api import YearsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestYearsApi(unittest.TestCase):
    """YearsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.years_api.YearsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_years_by_id_get(self):
        """Test case for years_by_id_get

        Rok o wybranym Id / Year with selected Id  # noqa: E501
        """
        pass

    def test_years_get(self):
        """Test case for years_get

        Lista lat obowiązywania danych / List of years of data availability  # noqa: E501
        """
        pass

    def test_years_metadata_get(self):
        """Test case for years_metadata_get

        Metadane / Metadata  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
