# coding: utf-8

"""
    BDL API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.single_unit_data import SingleUnitData  # noqa: E501
from swagger_client.rest import ApiException


class TestSingleUnitData(unittest.TestCase):
    """SingleUnitData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSingleUnitData(self):
        """Test SingleUnitData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.single_unit_data.SingleUnitData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
