# coding: utf-8

"""
    BDL API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.data_api import DataApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDataApi(unittest.TestCase):
    """DataApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.data_api.DataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_data_by_unit_get(self):
        """Test case for data_by_unit_get

        Dane dla jednej jednostki terytorialnej / Data for single territorial unit  # noqa: E501
        """
        pass

    def test_data_by_variable_get(self):
        """Test case for data_by_variable_get

        Dane dla jednej zmiennej / Data for single variable  # noqa: E501
        """
        pass

    def test_data_localities_by_unit_get(self):
        """Test case for data_localities_by_unit_get

        Dane dla jednej miejscowości statystycznej / Data for single statistical locality  # noqa: E501
        """
        pass

    def test_data_localities_by_variable_get(self):
        """Test case for data_localities_by_variable_get

        Dane dla miejscowości statystycznych dla jednej zmiennej / Data for statistical localities for single variable  # noqa: E501
        """
        pass

    def test_data_metadata_get(self):
        """Test case for data_metadata_get

        Metadane / Metadata  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
