# coding: utf-8

"""
    BDL API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.year_value import YearValue  # noqa: E501
from swagger_client.rest import ApiException


class TestYearValue(unittest.TestCase):
    """YearValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testYearValue(self):
        """Test YearValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.year_value.YearValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
