# coding: utf-8

"""
    BDL API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.subject_list import SubjectList  # noqa: E501
from swagger_client.rest import ApiException


class TestSubjectList(unittest.TestCase):
    """SubjectList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubjectList(self):
        """Test SubjectList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.subject_list.SubjectList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
