# coding: utf-8

"""
    BDL API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.attributes_api import AttributesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAttributesApi(unittest.TestCase):
    """AttributesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.attributes_api.AttributesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_attributes_by_id_get(self):
        """Test case for attributes_by_id_get

        Atrybut o zadanym Id / Atrribute with selected Id  # noqa: E501
        """
        pass

    def test_attributes_get(self):
        """Test case for attributes_get

        Lista atrybutów / Attributes list  # noqa: E501
        """
        pass

    def test_attributes_metadata_get(self):
        """Test case for attributes_metadata_get

        Metadane / Metadata  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
