# coding: utf-8

"""
    BDL API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.subjects_api import SubjectsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSubjectsApi(unittest.TestCase):
    """SubjectsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.subjects_api.SubjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_subjects_by_id_get(self):
        """Test case for subjects_by_id_get

        Temat o zadanym / Subject with selected Id  # noqa: E501
        """
        pass

    def test_subjects_get(self):
        """Test case for subjects_get

        Lista tematów / Subjects list  # noqa: E501
        """
        pass

    def test_subjects_metadata_get(self):
        """Test case for subjects_metadata_get

        Metadane / Metadata  # noqa: E501
        """
        pass

    def test_subjects_search_get(self):
        """Test case for subjects_search_get

        Wyszukiwanie tematów wg nazwy / Searching subjects by name  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
