# coding: utf-8

"""
    BDL API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.unit_list import UnitList  # noqa: E501
from swagger_client.rest import ApiException


class TestUnitList(unittest.TestCase):
    """UnitList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnitList(self):
        """Test UnitList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.unit_list.UnitList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
