# coding: utf-8

"""
    BDL API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.version_api import VersionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVersionApi(unittest.TestCase):
    """VersionApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.version_api.VersionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_version_get(self):
        """Test case for version_get

        Wersja aplikacji / Application version  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
