# coding: utf-8

"""
    BDL API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.year import Year  # noqa: E501
from swagger_client.rest import ApiException


class TestYear(unittest.TestCase):
    """Year unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testYear(self):
        """Test Year"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.year.Year()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
