# coding: utf-8

"""
    BDL API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Aggregate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'level': 'int',
        'description': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'level': 'level',
        'description': 'description'
    }

    def __init__(self, id=None, name=None, level=None, description=None):  # noqa: E501
        """Aggregate - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._level = None
        self._description = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if level is not None:
            self.level = level
        if description is not None:
            self.description = description

    @property
    def id(self):
        """Gets the id of this Aggregate.  # noqa: E501

        Identyfikator agregatu / Aggregate's identifier  # noqa: E501

        :return: The id of this Aggregate.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Aggregate.

        Identyfikator agregatu / Aggregate's identifier  # noqa: E501

        :param id: The id of this Aggregate.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Aggregate.  # noqa: E501

        Nazwa agregatu / Aggregate's name  # noqa: E501

        :return: The name of this Aggregate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Aggregate.

        Nazwa agregatu / Aggregate's name  # noqa: E501

        :param name: The name of this Aggregate.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def level(self):
        """Gets the level of this Aggregate.  # noqa: E501

        Poziom dostępności / Availability level  # noqa: E501

        :return: The level of this Aggregate.  # noqa: E501
        :rtype: int
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this Aggregate.

        Poziom dostępności / Availability level  # noqa: E501

        :param level: The level of this Aggregate.  # noqa: E501
        :type: int
        """

        self._level = level

    @property
    def description(self):
        """Gets the description of this Aggregate.  # noqa: E501

        Opis agregatu / Aggregate's description  # noqa: E501

        :return: The description of this Aggregate.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Aggregate.

        Opis agregatu / Aggregate's description  # noqa: E501

        :param description: The description of this Aggregate.  # noqa: E501
        :type: str
        """

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Aggregate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Aggregate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
