# coding: utf-8

"""
    BDL API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SingleUnitData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'total_records': 'int',
        'page': 'int',
        'page_size': 'int',
        'links': 'PageLinks',
        'unit_id': 'str',
        'unit_name': 'str',
        'aggregate_id': 'int',
        'results': 'list[VariableData]'
    }

    attribute_map = {
        'total_records': 'totalRecords',
        'page': 'page',
        'page_size': 'pageSize',
        'links': 'links',
        'unit_id': 'unitId',
        'unit_name': 'unitName',
        'aggregate_id': 'aggregateId',
        'results': 'results'
    }

    def __init__(self, total_records=None, page=None, page_size=None, links=None, unit_id=None, unit_name=None, aggregate_id=None, results=None):  # noqa: E501
        """SingleUnitData - a model defined in Swagger"""  # noqa: E501

        self._total_records = None
        self._page = None
        self._page_size = None
        self._links = None
        self._unit_id = None
        self._unit_name = None
        self._aggregate_id = None
        self._results = None
        self.discriminator = None

        if total_records is not None:
            self.total_records = total_records
        if page is not None:
            self.page = page
        if page_size is not None:
            self.page_size = page_size
        if links is not None:
            self.links = links
        if unit_id is not None:
            self.unit_id = unit_id
        if unit_name is not None:
            self.unit_name = unit_name
        if aggregate_id is not None:
            self.aggregate_id = aggregate_id
        if results is not None:
            self.results = results

    @property
    def total_records(self):
        """Gets the total_records of this SingleUnitData.  # noqa: E501

          # noqa: E501

        :return: The total_records of this SingleUnitData.  # noqa: E501
        :rtype: int
        """
        return self._total_records

    @total_records.setter
    def total_records(self, total_records):
        """Sets the total_records of this SingleUnitData.

          # noqa: E501

        :param total_records: The total_records of this SingleUnitData.  # noqa: E501
        :type: int
        """

        self._total_records = total_records

    @property
    def page(self):
        """Gets the page of this SingleUnitData.  # noqa: E501

          # noqa: E501

        :return: The page of this SingleUnitData.  # noqa: E501
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page):
        """Sets the page of this SingleUnitData.

          # noqa: E501

        :param page: The page of this SingleUnitData.  # noqa: E501
        :type: int
        """

        self._page = page

    @property
    def page_size(self):
        """Gets the page_size of this SingleUnitData.  # noqa: E501

          # noqa: E501

        :return: The page_size of this SingleUnitData.  # noqa: E501
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size):
        """Sets the page_size of this SingleUnitData.

          # noqa: E501

        :param page_size: The page_size of this SingleUnitData.  # noqa: E501
        :type: int
        """

        self._page_size = page_size

    @property
    def links(self):
        """Gets the links of this SingleUnitData.  # noqa: E501


        :return: The links of this SingleUnitData.  # noqa: E501
        :rtype: PageLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this SingleUnitData.


        :param links: The links of this SingleUnitData.  # noqa: E501
        :type: PageLinks
        """

        self._links = links

    @property
    def unit_id(self):
        """Gets the unit_id of this SingleUnitData.  # noqa: E501

        Identyfikator jednostki / Unit's identifier  # noqa: E501

        :return: The unit_id of this SingleUnitData.  # noqa: E501
        :rtype: str
        """
        return self._unit_id

    @unit_id.setter
    def unit_id(self, unit_id):
        """Sets the unit_id of this SingleUnitData.

        Identyfikator jednostki / Unit's identifier  # noqa: E501

        :param unit_id: The unit_id of this SingleUnitData.  # noqa: E501
        :type: str
        """

        self._unit_id = unit_id

    @property
    def unit_name(self):
        """Gets the unit_name of this SingleUnitData.  # noqa: E501

        Nazwa jednostki / Unit's name  # noqa: E501

        :return: The unit_name of this SingleUnitData.  # noqa: E501
        :rtype: str
        """
        return self._unit_name

    @unit_name.setter
    def unit_name(self, unit_name):
        """Sets the unit_name of this SingleUnitData.

        Nazwa jednostki / Unit's name  # noqa: E501

        :param unit_name: The unit_name of this SingleUnitData.  # noqa: E501
        :type: str
        """

        self._unit_name = unit_name

    @property
    def aggregate_id(self):
        """Gets the aggregate_id of this SingleUnitData.  # noqa: E501

        Identyfikator agregatu / Aggregate's identifier  # noqa: E501

        :return: The aggregate_id of this SingleUnitData.  # noqa: E501
        :rtype: int
        """
        return self._aggregate_id

    @aggregate_id.setter
    def aggregate_id(self, aggregate_id):
        """Sets the aggregate_id of this SingleUnitData.

        Identyfikator agregatu / Aggregate's identifier  # noqa: E501

        :param aggregate_id: The aggregate_id of this SingleUnitData.  # noqa: E501
        :type: int
        """

        self._aggregate_id = aggregate_id

    @property
    def results(self):
        """Gets the results of this SingleUnitData.  # noqa: E501

        Wartości dla zmiennych / Values for variables  # noqa: E501

        :return: The results of this SingleUnitData.  # noqa: E501
        :rtype: list[VariableData]
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this SingleUnitData.

        Wartości dla zmiennych / Values for variables  # noqa: E501

        :param results: The results of this SingleUnitData.  # noqa: E501
        :type: list[VariableData]
        """

        self._results = results

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SingleUnitData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SingleUnitData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
