# coding: utf-8

"""
    BDL API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class VariableData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'measure_unit_id': 'int',
        'last_update': 'datetime',
        'values': 'list[YearValue]'
    }

    attribute_map = {
        'id': 'id',
        'measure_unit_id': 'measureUnitId',
        'last_update': 'lastUpdate',
        'values': 'values'
    }

    def __init__(self, id=None, measure_unit_id=None, last_update=None, values=None):  # noqa: E501
        """VariableData - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._measure_unit_id = None
        self._last_update = None
        self._values = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if measure_unit_id is not None:
            self.measure_unit_id = measure_unit_id
        if last_update is not None:
            self.last_update = last_update
        if values is not None:
            self.values = values

    @property
    def id(self):
        """Gets the id of this VariableData.  # noqa: E501

        Identyfikator zmiennej / Variable's identifier  # noqa: E501

        :return: The id of this VariableData.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this VariableData.

        Identyfikator zmiennej / Variable's identifier  # noqa: E501

        :param id: The id of this VariableData.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def measure_unit_id(self):
        """Gets the measure_unit_id of this VariableData.  # noqa: E501

        Identyfikator jednostki miary / Measure unit's identifier  # noqa: E501

        :return: The measure_unit_id of this VariableData.  # noqa: E501
        :rtype: int
        """
        return self._measure_unit_id

    @measure_unit_id.setter
    def measure_unit_id(self, measure_unit_id):
        """Sets the measure_unit_id of this VariableData.

        Identyfikator jednostki miary / Measure unit's identifier  # noqa: E501

        :param measure_unit_id: The measure_unit_id of this VariableData.  # noqa: E501
        :type: int
        """

        self._measure_unit_id = measure_unit_id

    @property
    def last_update(self):
        """Gets the last_update of this VariableData.  # noqa: E501

        Data ostatniej modyfikacji / Last update  # noqa: E501

        :return: The last_update of this VariableData.  # noqa: E501
        :rtype: datetime
        """
        return self._last_update

    @last_update.setter
    def last_update(self, last_update):
        """Sets the last_update of this VariableData.

        Data ostatniej modyfikacji / Last update  # noqa: E501

        :param last_update: The last_update of this VariableData.  # noqa: E501
        :type: datetime
        """

        self._last_update = last_update

    @property
    def values(self):
        """Gets the values of this VariableData.  # noqa: E501

        Lista wartości w latach / Value in years list  # noqa: E501

        :return: The values of this VariableData.  # noqa: E501
        :rtype: list[YearValue]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this VariableData.

        Lista wartości w latach / Value in years list  # noqa: E501

        :param values: The values of this VariableData.  # noqa: E501
        :type: list[YearValue]
        """

        self._values = values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VariableData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VariableData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
